# Generated by Django 4.1.3 on 2022-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=512)),
            ],
        ),
    ]
